window.exam2ExtraQuestions = [
["Which statement best describes the epidermis?",["It is avascular keratinized stratified squamous epithelium","It is dense irregular connective tissue","It is made mostly of adipose tissue","It contains large blood vessels"],0,"The epidermis is keratinized stratified squamous epithelium and has no blood vessels; nutrients diffuse up from the dermis.",5],
["Which epidermal cell is responsible for producing keratin?",["Melanocyte","Keratinocyte","Tactile cell","Dendritic cell"],1,"Keratinocytes are the dominant epidermal cells and produce keratin.",5],
["Which epidermal cell produces melanin?",["Keratinocyte","Melanocyte","Fibroblast","Osteoblast"],1,"Melanocytes in the stratum basale produce melanin.",5],
["Which epidermal cells function as antigen-presenting immune cells?",["Dendritic cells","Tactile cells","Adipocytes","Chondrocytes"],0,"Epidermal dendritic cells, also called Langerhans cells, participate in immune defense and antigen presentation.",5],
["Which epidermal layer is found only in thick skin?",["Stratum spinosum","Stratum granulosum","Stratum lucidum","Stratum basale"],2,"The stratum lucidum is present in thick skin such as palms and soles.",5],
["What is the correct order of epidermal strata from deep to superficial in thick skin?",["Basale, spinosum, granulosum, lucidum, corneum","Corneum, lucidum, granulosum, spinosum, basale","Basale, granulosum, spinosum, lucidum, corneum","Spinosum, basale, granulosum, corneum, lucidum"],0,"Deep to superficial: basale → spinosum → granulosum → lucidum → corneum.",5],
["The papillary layer of the dermis is composed mainly of:",["Dense regular connective tissue","Areolar connective tissue","Hyaline cartilage","Adipose tissue"],1,"The papillary dermis is primarily areolar connective tissue.",5],
["The reticular layer of the dermis is composed mainly of:",["Dense irregular connective tissue","Simple squamous epithelium","Elastic cartilage","Dense regular connective tissue"],0,"The reticular dermis is dense irregular connective tissue rich in collagen and elastic fibers.",5],
["Which skin structure contracts to produce goose bumps?",["Sebaceous gland","Arrector pili muscle","Eccrine gland","Hair matrix"],1,"Arrector pili are smooth muscles attached to hair follicles.",5],
["Which gland releases sebum?",["Sebaceous gland","Merocrine sweat gland","Apocrine sweat gland","Ceruminous gland"],0,"Sebaceous glands produce oily sebum, typically into hair follicles.",5],
["Which sweat glands are most important for evaporative cooling?",["Apocrine glands","Merocrine/eccrine glands","Sebaceous glands","Mammary glands"],1,"Merocrine, or eccrine, sweat glands are widely distributed and play the major role in thermoregulation.",5],
["Apocrine sweat glands are concentrated mainly in the:",["Palms and soles","Axillary and anogenital regions","Scalp only","Forearms and legs"],1,"Apocrine sweat glands are concentrated in the axillary and anogenital regions.",5],
["Which pigment is produced by melanocytes?",["Carotene","Melanin","Hemoglobin","Keratin"],1,"Melanocytes produce melanin.",5],
["Which organ completes the conversion of vitamin D to calcitriol?",["Liver","Kidney","Skin","Pancreas"],1,"Skin begins vitamin D3 production, the liver modifies it, and the kidney completes activation to calcitriol.",5],
["A full-thickness burn destroys:",["Only the epidermis","Epidermis and dermis","Only the stratum corneum","Only the hypodermis"],1,"Full-thickness burns destroy the epidermis and dermis and may require grafting.",5],
["Insensible perspiration refers to:",["Visible sweating during exercise","Continuous water loss that is not noticed","Oil secretion from sebaceous glands","Sweat produced only by apocrine glands"],1,"Insensible perspiration is continuous, unnoticeable water loss through the skin.",5],

["Which bone cell secretes osteoid?",["Osteoclast","Osteoblast","Osteocyte","Chondrocyte"],1,"Osteoblasts form new bone by secreting osteoid.",6],
["Which bone cell resorbs bone matrix?",["Osteoblast","Osteocyte","Osteoclast","Osteogenic cell"],2,"Osteoclasts break down and resorb bone matrix.",6],
["Mature bone cells located in lacunae are:",["Osteocytes","Osteoclasts","Osteoblasts","Fibroblasts"],0,"Osteocytes are mature bone cells housed in lacunae.",6],
["The shaft of a long bone is the:",["Epiphysis","Diaphysis","Metaphysis","Condyle"],1,"The diaphysis is the shaft of a long bone.",6],
["The ends of a long bone are the:",["Epiphyses","Diaphyses","Osteons","Canaliculi"],0,"The proximal and distal ends of a long bone are the epiphyses.",6],
["Which membrane lines the medullary cavity?",["Periosteum","Endosteum","Perimysium","Synovium"],1,"Endosteum lines internal bone surfaces including the medullary cavity.",6],
["Which membrane covers most external bone surfaces?",["Endosteum","Periosteum","Endomysium","Synovial membrane"],1,"Periosteum covers external bone surfaces except where articular cartilage is present.",6],
["What is the basic structural unit of compact bone?",["Trabecula","Osteon","Lacuna","Epiphyseal plate"],1,"Compact bone is organized into osteons, also called Haversian systems.",6],
["The central canal of an osteon contains primarily:",["Blood vessels and nerves","Yellow marrow only","Chondrocytes","Synovial fluid"],0,"Central canals carry vessels and nerves through compact bone.",6],
["Canaliculi function to:",["Connect lacunae and allow osteocyte communication","Form articular cartilage","Store yellow marrow","Attach tendons to bone"],0,"Canaliculi are tiny channels connecting osteocytes in neighboring lacunae.",6],
["Spongy bone is organized into:",["Osteons only","Trabeculae","Fascicles","Sarcomeres"],1,"Spongy bone is arranged as a lattice of trabeculae.",6],
["Intramembranous ossification begins within:",["A hyaline cartilage model","Mesenchymal connective tissue","A synovial cavity","Dense regular connective tissue"],1,"Intramembranous ossification develops directly from mesenchymal connective tissue.",6],
["Endochondral ossification begins with:",["A hyaline cartilage model","A fibrous membrane only","Compact bone","A tendon"],0,"Endochondral ossification replaces a preexisting hyaline cartilage model.",6],
["Growth in length of a long bone occurs at the:",["Periosteum","Epiphyseal plate","Medullary cavity","Central canal"],1,"Longitudinal growth occurs at the epiphyseal plate.",6],
["Appositional growth increases bone:",["Length","Diameter","Number of joints","Number of epiphyses"],1,"Appositional growth increases bone diameter.",6],
["Which hormone is released when blood calcium is low?",["Calcitonin","Parathyroid hormone","Insulin","Thyroxine"],1,"Low blood calcium stimulates parathyroid hormone secretion.",6],
["What is the first major event in fracture repair?",["Bony callus","Fracture hematoma","Remodeling","Epiphyseal closure"],1,"Fracture repair begins with formation of a hematoma.",6],

["How many bones are in the adult axial skeleton?",["80","126","206","64"],0,"The adult axial skeleton contains 80 bones.",7],
["Which of the following belongs to the axial skeleton?",["Scapula","Clavicle","Sternum","Femur"],2,"The sternum is part of the thoracic cage and therefore the axial skeleton.",7],
["Which cranial bone contains the foramen magnum?",["Frontal","Occipital","Sphenoid","Temporal"],1,"The foramen magnum is located in the occipital bone.",7],
["How many cervical vertebrae are there?",["5","7","12","24"],1,"There are 7 cervical vertebrae.",7],
["How many thoracic vertebrae are there?",["5","7","12","24"],2,"There are 12 thoracic vertebrae.",7],
["How many lumbar vertebrae are there?",["5","7","12","2"],0,"There are 5 lumbar vertebrae.",7],
["The atlas is which vertebra?",["C1","C2","T1","L1"],0,"The atlas is the first cervical vertebra, C1.",7],
["The dens is a feature of the:",["Atlas","Axis","Sacrum","Occipital bone"],1,"The axis, C2, has the dens.",7],
["Which vertebrae contain transverse foramina?",["Cervical","Thoracic","Lumbar","Sacral only"],0,"Transverse foramina are characteristic of cervical vertebrae.",7],
["Which spinal curves are primary curves?",["Cervical and lumbar","Thoracic and sacral","Cervical and thoracic","Lumbar and sacral"],1,"Thoracic and sacral curves are present at birth and are primary curves.",7],
["Which spinal curves are secondary curves?",["Thoracic and sacral","Cervical and lumbar","Thoracic and lumbar","Cervical and sacral"],1,"Cervical and lumbar curves develop after birth and are secondary curves.",7],
["The gel-like center of an intervertebral disc is the:",["Anulus fibrosus","Nucleus pulposus","Spinous process","Vertebral foramen"],1,"The nucleus pulposus forms the gel-like core of an intervertebral disc.",7],
["The outer fibrous portion of an intervertebral disc is the:",["Nucleus pulposus","Anulus fibrosus","Dens","Lamina"],1,"The anulus fibrosus forms the tough outer ring.",7],
["Which ribs are true ribs?",["1–7","8–10","11–12","1–5 only"],0,"Ribs 1 through 7 attach directly to the sternum by their own costal cartilages.",7],
["Which ribs are floating ribs?",["1–2","6–7","8–10","11–12"],3,"Ribs 11 and 12 are floating ribs because they lack anterior attachment to the sternum.",7],
["The sternum consists of the manubrium, body, and:",["Acromion","Xiphoid process","Coracoid process","Olecranon"],1,"The sternum has a manubrium, body, and xiphoid process.",7],

["How many bones are in the adult appendicular skeleton?",["80","126","206","60"],1,"The appendicular skeleton contains 126 bones.",8],
["The pectoral girdle consists of the:",["Clavicle and scapula","Radius and ulna","Femur and tibia","Sacrum and coccyx"],0,"Each pectoral girdle contains a clavicle and scapula.",8],
["The glenoid cavity articulates with the:",["Head of the femur","Head of the humerus","Radius","Clavicle"],1,"The glenoid cavity of the scapula receives the head of the humerus.",8],
["The arm bone is the:",["Radius","Ulna","Humerus","Scapula"],2,"The humerus is the bone of the arm.",8],
["In anatomical position, the radius is on the:",["Medial side of the forearm","Lateral/thumb side of the forearm","Posterior side only","Same side as the little finger"],1,"The radius is lateral, on the thumb side.",8],
["In anatomical position, the ulna is on the:",["Lateral/thumb side","Medial/little-finger side","Anterior side only","Same side as the great toe"],1,"The ulna is medial, on the little-finger side.",8],
["How many carpal bones are in one wrist?",["5","7","8","14"],2,"Each wrist contains 8 carpal bones.",8],
["How many metacarpals are in one hand?",["5","8","14","7"],0,"Each hand contains 5 metacarpals.",8],
["How many phalanges are in one hand?",["8","10","12","14"],3,"Each hand contains 14 phalanges.",8],
["The hip bone is formed by fusion of the:",["Ilium, ischium, and pubis","Femur, tibia, and fibula","Sacrum, coccyx, and pubis","Ilium, sacrum, and femur"],0,"The os coxae forms from ilium, ischium, and pubis.",8],
["The acetabulum receives the head of the:",["Humerus","Femur","Radius","Tibia"],1,"The acetabulum is the hip socket that receives the femoral head.",8],
["Which is the main weight-bearing bone of the leg?",["Fibula","Tibia","Patella","Talus"],1,"The tibia is the larger, medial, weight-bearing bone of the leg.",8],
["Which bone is lateral in the leg?",["Tibia","Fibula","Femur","Patella"],1,"The fibula is the slender lateral bone of the leg.",8],
["The patella is classified as a:",["Flat bone","Long bone","Sesamoid bone","Irregular bone"],2,"The patella is a sesamoid bone embedded in the quadriceps tendon.",8],
["Which tarsal bone forms the heel?",["Talus","Calcaneus","Navicular","Cuboid"],1,"The calcaneus forms the heel.",8],
["Which tarsal articulates with the tibia at the ankle?",["Calcaneus","Talus","Cuboid","Navicular"],1,"The talus articulates with the tibia at the ankle joint.",8],

["A synarthrosis is a joint that is:",["Freely movable","Slightly movable","Immovable","Always synovial"],2,"Synarthrosis is the functional class for an immovable joint.",9],
["An amphiarthrosis is a joint that is:",["Immovable","Slightly movable","Freely movable","Only found in the skull"],1,"Amphiarthroses allow slight movement.",9],
["A diarthrosis is a joint that is:",["Immovable","Slightly movable","Freely movable","Always fibrous"],2,"Diarthroses are freely movable joints.",9],
["All synovial joints are functionally classified as:",["Synarthroses","Amphiarthroses","Diarthroses","Synchondroses"],2,"Synovial joints are freely movable and therefore diarthroses.",9],
["Which structural joint class has a fluid-filled joint cavity?",["Fibrous","Cartilaginous","Synovial","Suture"],2,"Synovial joints have a joint cavity containing synovial fluid.",9],
["Which structure covers the ends of bones in a synovial joint?",["Articular cartilage","Periosteum only","Endosteum","Dense regular cartilage"],0,"Articular hyaline cartilage covers opposing bone surfaces in synovial joints.",9],
["The inner layer of a synovial joint capsule is the:",["Fibrous layer","Synovial membrane","Periosteum","Endosteum"],1,"The synovial membrane lines the inside of the capsule and produces synovial fluid.",9],
["What is the main function of synovial fluid?",["Lubricate the joint","Produce red blood cells","Attach muscle to bone","Mineralize cartilage"],0,"Synovial fluid lubricates, nourishes articular cartilage, and helps absorb shock.",9],
["A bursa primarily functions to:",["Reduce friction","Store calcium","Produce bone marrow","Connect bone to bone"],0,"Bursae are fluid-filled sacs that reduce friction between moving tissues.",9],
["Ligaments connect:",["Muscle to bone","Bone to bone","Bone to skin","Nerve to muscle"],1,"Ligaments connect bone to bone.",9],
["Flexion generally:",["Increases the angle at a joint","Decreases the angle at a joint","Moves away from midline","Rotates the forearm palm-up"],1,"Flexion generally decreases the angle between articulating bones.",9],
["Extension generally:",["Decreases the angle at a joint","Increases the angle at a joint","Moves toward midline","Turns the sole inward"],1,"Extension generally increases the angle at a joint.",9],
["Abduction moves a body part:",["Toward the midline","Away from the midline","Inferiorly only","Into flexion only"],1,"Abduction moves away from the midline.",9],
["Adduction moves a body part:",["Away from the midline","Toward the midline","Into rotation only","Posteriorly only"],1,"Adduction moves toward the midline.",9],
["Standing on tiptoe requires:",["Dorsiflexion","Plantar flexion","Inversion","Eversion"],1,"Plantar flexion points the foot downward, as when standing on tiptoe.",9],
["The thumb carpometacarpal joint is a:",["Hinge joint","Pivot joint","Saddle joint","Plane joint"],2,"The first carpometacarpal joint is a saddle joint.",9],

["Which connective tissue sheath surrounds an entire skeletal muscle?",["Endomysium","Perimysium","Epimysium","Sarcolemma"],2,"Epimysium surrounds the whole muscle.",10],
["Which connective tissue sheath surrounds a fascicle?",["Epimysium","Perimysium","Endomysium","Sarcolemma"],1,"Perimysium surrounds a fascicle.",10],
["Which connective tissue sheath surrounds an individual muscle fiber?",["Epimysium","Perimysium","Endomysium","Tendon"],2,"Endomysium surrounds each muscle fiber.",10],
["The plasma membrane of a muscle fiber is the:",["Sarcolemma","Sarcoplasm","Sarcoplasmic reticulum","Perimysium"],0,"The sarcolemma is the muscle fiber's plasma membrane.",10],
["The functional contractile unit of skeletal muscle is the:",["Myofibril","Sarcomere","Fascicle","Motor unit"],1,"A sarcomere is the repeating contractile unit between Z lines.",10],
["A sarcomere extends from:",["M line to M line","Z line to Z line","A band to A band","H zone to H zone"],1,"Each sarcomere extends from one Z line to the next.",10],
["Thin filaments are composed mainly of:",["Myosin","Actin","Collagen","Titin only"],1,"Thin filaments are primarily actin with troponin and tropomyosin.",10],
["Thick filaments are composed mainly of:",["Actin","Myosin","Troponin","Tropomyosin"],1,"Thick filaments are made primarily of myosin.",10],
["During contraction, which band remains the same width?",["I band","H zone","A band","Z disc"],2,"The A band corresponds to thick-filament length and remains constant.",10],
["During contraction, the I band:",["Gets wider","Gets smaller","Stays the same","Disappears in every contraction"],1,"The I band narrows as thin filaments slide toward the center.",10],
["During contraction, the Z lines:",["Move farther apart","Move closer together","Stay fixed in space","Become thick filaments"],1,"Z lines move closer as the sarcomere shortens.",10],
["At the neuromuscular junction, the motor neuron releases:",["Calcium","Acetylcholine","Troponin","Myosin"],1,"Motor neurons release acetylcholine into the synaptic cleft.",10],
["Which enzyme breaks down acetylcholine in the synaptic cleft?",["ATP synthase","Acetylcholinesterase","Creatine kinase","Myosin ATPase"],1,"Acetylcholinesterase terminates the ACh signal.",10],
["T tubules carry the muscle action potential:",["Deep into the muscle fiber","Only along the tendon","Into the nucleus","Out of the cell"],0,"T tubules rapidly conduct depolarization deep into the fiber.",10],
["Calcium for skeletal muscle contraction is stored mainly in the:",["Golgi apparatus","Sarcoplasmic reticulum","Nucleus","Lysosome"],1,"The sarcoplasmic reticulum stores and releases Ca2+.",10],
["Calcium binds to:",["Tropomyosin","Troponin","Myosin tail","Actin active site"],1,"Calcium binds troponin, causing tropomyosin to shift.",10],
["What directly exposes the myosin-binding sites on actin?",["Tropomyosin moves away","Myosin leaves the thick filament","ATP disappears","ACh enters the sarcomere"],0,"Calcium binding to troponin shifts tropomyosin away from actin's active sites.",10],
["What causes myosin to detach from actin?",["A new ATP binds to myosin","Calcium binds to troponin","ACh binds to receptors","The Z line breaks"],0,"ATP binding to myosin causes cross-bridge detachment.",10],
["A motor unit consists of:",["One motor neuron and all muscle fibers it innervates","One fascicle and one tendon","One sarcomere and one nerve","All fibers in a muscle"],0,"A motor unit is a motor neuron plus all of the muscle fibers it controls.",10],
["A contraction that develops tension without changing muscle length is:",["Concentric","Eccentric","Isometric","Isotonic only"],2,"In an isometric contraction, tension rises without a change in overall muscle length.",10],
["A contraction in which the active muscle shortens is:",["Concentric","Eccentric","Isometric","Tetanic only"],0,"Concentric contractions shorten the active muscle.",10],
["A contraction in which the active muscle lengthens is:",["Concentric","Eccentric","Isometric","Latent"],1,"Eccentric contractions occur while the active muscle is lengthening.",10],
["Which compound rapidly donates phosphate to regenerate ATP?",["Creatine phosphate","Troponin","Myoglobin","Acetylcholine"],0,"Creatine phosphate provides a rapid short-term source for ATP regeneration.",10],
["Which fiber type is most resistant to fatigue?",["Slow oxidative","Fast glycolytic","All fiber types are equal","Smooth muscle only"],0,"Slow oxidative fibers have many mitochondria, capillaries, and myoglobin and resist fatigue.",10],
["Resistance training most directly promotes:",["Hypertrophy","Atrophy","Loss of mitochondria only","Loss of contractile proteins"],0,"Resistance training promotes muscle hypertrophy.",10],
["Endurance training most directly improves:",["Aerobic capacity","Bone marrow volume","Sebum production","Joint capsule thickness only"],0,"Endurance training improves oxidative capacity, capillary support, and fatigue resistance.",10]
];